### ISSUE TITLE
docker-rails-elasticsearch-1 exited with code 137

### ISSUE THREAD

**Issue by x1wins** [ledermann/docker-rails#2617]
i got elasticsearch error with ```docker-rails-elasticsearch-1 exited with code 137```
elasticsearch was not running.

```bash
docker-rails-elasticsearch-1  | {"type": "server", "timestamp": "2022-02-27T04:31:48,611Z", "level": "INFO", "component": "o.e.i.g.GeoIpDownloader", "cluster.name": "docker-cluster", "node.name": "69b0e8b669a8", "message": "updated geoip database [GeoLite2-ASN.mmdb]", "cluster.uuid": "oVWhq53zQrOjnrQ1oRXFFA", "node.id": "Kpnd4j2MSoKa0jCfbCc1Yw"  }
docker-rails-elasticsearch-1  | {"type": "server", "timestamp": "2022-02-27T04:31:48,629Z", "level": "INFO", "component": "o.e.i.g.GeoIpDownloader", "cluster.name": "docker-cluster", "node.name": "69b0e8b669a8", "message": "updating geoip database [GeoLite2-City.mmdb]", "cluster.uuid": "oVWhq53zQrOjnrQ1oRXFFA", "node.id": "Kpnd4j2MSoKa0jCfbCc1Yw"  }
docker-rails-elasticsearch-1  | {"type": "server", "timestamp": "2022-02-27T04:31:48,921Z", "level": "INFO", "component": "o.e.i.g.DatabaseNodeService", "cluster.name": "docker-cluster", "node.name": "69b0e8b669a8", "message": "successfully reloaded changed geoip database file [/tmp/elasticsearch-5151365541444706863/geoip-databases/Kpnd4j2MSoKa0jCfbCc1Yw/GeoLite2-ASN.mmdb]", "cluster.uuid": "oVWhq53zQrOjnrQ1oRXFFA", "node.id": "Kpnd4j2MSoKa0jCfbCc1Yw"  }
docker-rails-elasticsearch-1 exited with code 137
docker-rails-worker-1         | 2022-02-27T04:31:57.917Z pid=1 tid=cp9 INFO: Booting Sidekiq 6.4.1 with redis options {:url=>"redis://redis:6379/0"}
docker-rails-worker-1         | 2022-02-27T04:31:57.958Z pid=1 tid=cp9 INFO: Cron Jobs - add job with name: wikipedia
docker-rails-worker-1         | 2022-02-27T04:32:02.043Z pid=1 tid=cp9 INFO: Booted Rails 7.0.2.2 application in production environment
docker-rails-worker-1         | 2022-02-27T04:32:02.044Z pid=1 tid=cp9 INFO: Running in ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-linux-musl]
docker-rails-worker-1         | 2022-02-27T04:32:02.044Z pid=1 tid=cp9 INFO: See LICENSE and the LGPL-3.0 for licensing details.
docker-rails-worker-1         | 2022-02-27T04:32:02.044Z pid=1 tid=cp9 INFO: Upgrade to Sidekiq Pro for more features and support: https://sidekiq.org
docker-rails-db-1             | 2022-02-27 04:32:04.762 UTC [56] FATAL:  database "docker-rails_production" does not exist
docker-rails-app-1            | Created database 'docker-rails_production'
docker-rails-app-1            | Create admin user...
docker-rails-app-1            | rake aborted!
docker-rails-app-1            | Faraday::ConnectionFailed: Failed to open TCP connection to elasticsearch:9200 (getaddrinfo: Name does not resolve)
docker-rails-app-1            | /usr/local/bundle/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:138:in `request_via_get_method'
docker-rails-app-1            | /usr/local/bundle/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:129:in `request_with_wrapped_block'
docker-rails-app-1            | /usr/local/bundle/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:122:in `perform_request'
docker-rails-app-1            | /usr/local/bundle/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:66:in `block in call'

```

**Comment by x1wins** [comment]
i found a solution.
my laptop used ```docker desktop 4.5.0 (74594)``` there was default setup with 2GB memory.
i changed 2GB to 4GB. it's working well.
https://github.com/10up/wp-local-docker/issues/6#issuecomment-285474874
<img width="1382" alt="image" src="https://user-images.githubusercontent.com/982291/155873125-229480ae-bb59-4ea8-8832-b49bf276a9cc.png">
